/***************************************************************************
Kitty MorphOS
 Copyright (C) 2022 digitally
***************************************************************************/
#ifndef LOCALE_H
#define LOCALE_H

// If this file is named 'Locale.h' it is automatically
// generated by 'FlexCat' from Locale_h.sd.
// PLEASE DO NOT EDIT!!!

// flexcat string structure
struct fcstr
{
  const char * const defmsg; // the default/fallback catalog string
  const char * msg;          // the translated/converted catalog string
  const long id;             // catalog string identifier
};

// catalog init/open/close functions
extern void InitCatalogue(void);
extern BOOL OpenCatalogue(void);
extern void CloseCatalogue(void);
extern char *GetStr(APTR fcstr);

// define to retrieve the translated catalog string
#define tr(fc)    ((fc)->msg)

// array of catalog translation strings
extern struct fcstr Kitty_Strings[36];

// the final MSG_XXXX defines pointing to the corresponding strings
#define MSG_MA_PROJECT (&Kitty_Strings[0])
#define MSG_MA_ABOUT (&Kitty_Strings[1])
#define MSG_MA_ABOUT_MUI (&Kitty_Strings[2])
#define MSG_PROJECT_ABOUT (&Kitty_Strings[3])
#define MSG_SETTINGS_MUI (&Kitty_Strings[4])
#define MSG_HIDE (&Kitty_Strings[5])
#define MSG_QUIT (&Kitty_Strings[6])
#define MSG_COPYRIGHT1 (&Kitty_Strings[7])
#define MSG_VERSION (&Kitty_Strings[8])
#define MSG_COMPILATION_DATE (&Kitty_Strings[9])
#define MSG_COPYRIGHT2 (&Kitty_Strings[10])
#define MSG_USED_SOFTWARE (&Kitty_Strings[11])
#define MSG_APPLICATION_DESCRIPTION (&Kitty_Strings[12])
#define MSG_OK (&Kitty_Strings[13])
#define MSG_CANCEL (&Kitty_Strings[14])
#define MSG_YES (&Kitty_Strings[15])
#define MSG_NO (&Kitty_Strings[16])
#define MSG_CREATING_GUI (&Kitty_Strings[17])
#define MSG_INIT_LIBS (&Kitty_Strings[18])
#define MSG_LOADING_GFX (&Kitty_Strings[19])
#define MSG_NO_MCC (&Kitty_Strings[20])
#define MSG_MCC_OLD (&Kitty_Strings[21])
#define MSG_MCC_IN_USE (&Kitty_Strings[22])
#define MSG_RETRY_QUIT_GAD (&Kitty_Strings[23])
#define MSG_OPENING_GUI (&Kitty_Strings[24])
#define MSG_QuitANGReq (&Kitty_Strings[25])
#define MSG_WINDOW_TITLE (&Kitty_Strings[26])
#define MSG_BT_QUIT (&Kitty_Strings[27])
#define MSG_ERROR_STARTUP (&Kitty_Strings[28])
#define MSG_ERROR_LIB (&Kitty_Strings[29])
#define MSG_ERROR_MUI_APPLICATION (&Kitty_Strings[30])
#define MSG_ERROR_CLASSES (&Kitty_Strings[31])
#define MSG_ERROR_TIMER (&Kitty_Strings[32])
#define MSG_ERROR_TASK (&Kitty_Strings[33])
#define MSG_ERROR_SIGNAL (&Kitty_Strings[34])
#define NUM_OF_MSGS (&Kitty_Strings[35])

#endif /* LOCALE_H */
